### ISSUE TITLE
Application Commands Part 2: Interactionhandler

### ISSUE THREAD

**Issue by diewellenlaenge** [NullDev/CSC-Bot#116]
## Bedingungen

- Bitte zu erst die Application Commands Übersicht lesen (#114)
- Geblockt von der Registrierung #115 (das muss zu erst erledigt werden)

## Beschreibung

Es muss ein Interactionhandler registriert werden, der die Anfragen an die einzelnen Module aufteilt. Dafür ist es notwendig, dass die App die Module und deren Commands kennt, um die Weiterleitung durchzuführen

## Todos

- [ ] App muss Infos über alle Commands haben
- [ ] Interactionhandler muss auf Application Commands reagieren
- [ ] Interactionhandler muss die Daten ans jeweilige Modul weitergeben

## Beispiele

Aus dem Fork:

- [Interactionhandler](https://github.com/NullDev/CSC-Bot/blob/slash-commands-ts/src/handler/interactionHandler.ts)
- [Event dafür](https://github.com/NullDev/CSC-Bot/blob/slash-commands-ts/src/app.js#L157)

**Comment by tobi6112** [comment]
Erledigt 96b074aa7365ec4717d49a0e831639707577052f
