### ISSUE TITLE
Application Commands Part 3: Messagehandler-Bridge

### ISSUE THREAD

**Issue by diewellenlaenge** [NullDev/CSC-Bot#117]
## Bedingungen

- Bitte zu erst die Application Commands Übersicht lesen (#114)
- Geblockt vom Interactionhandler #116 (das muss zu erst erledigt werden)

## Beschreibung

Da auch weiterhin einige Application Commands in Zukunft (und für die Übergangszeit, bis alles migriert wurde) per `.`-Befehl nutzbar sein muss, benötigen wir einen Messagehandler, der als eine Art Bridge fungiert und klassische Befehle in Application Commands übersetzen kann.

## Todos

- [x] Messagehandler über Application Commands informieren
- [x] Callbacks in den Modulen müssen mit beiden Arten von Inputs (klassisch und Application Command) umgehen können (wo nötig, z. B. `.mock`)
- [x] Messagehandler muss irgendwie eine Interaction emulieren (oder so?)

## Beispiele

Aus dem Fork:

- [Messagehandler](https://github.com/NullDev/CSC-Bot/blob/slash-commands-ts/src/handler/commands.ts#L78-L156)
- [alter Messagehandle](https://github.com/NullDev/CSC-Bot/blob/slash-commands-ts/src/handler/messageHandler.js#L212-L267)
