### ISSUE TITLE
Application Commands Part 4: Stateful Commands

### ISSUE THREAD

**Issue by diewellenlaenge** [NullDev/CSC-Bot#118]
## Bedingungen

- Bitte zu erst die Application Commands Übersicht lesen (#114)
- Geblockt von der Messagehandler-Bridge #117 (das muss zu erst erledigt werden)

## Beschreibung

Damit das volle Potential von Application Commands genutzt werden kann, sollten die Module irgendwie mit States umgehen können. Dies ist beispielsweise notwendig für anonyme Polls oder Woisgang-Abfragen. Bisher bastelt jedes Modul sich seinen eigenen temporären Store. Das ist kacke, weil der verloren geht, wenn der Bot neustartet.

## Todos

- [ ] Konzept ausarbeiten (bisher existiert dazu noch nichts)
- [ ] Irgendwie versuchen, das mit Sequelize o. ä. zu lösen, damit der State auch einen Restart überlebt
- [ ] Das irgendwie versuchen, generisch zu halten, sodass jedes Modul sich einen eigenen State bauen kann
